creditsgfx:
creditssize equ 644
        db $00
        db $7F
        db $FF
        db $07
        db $FF
        db $C0
        db $0F
        db $FF
        db $FC
        db $1F
        db $FF
        db $00
        db $7F
        db $FE
        db $1F
        db $FF
        db $FE
        db $01
        db $FF
        db $FC
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $80
        db $51
        db $FF
        db $10
        db $D4
        db $0F
        db $08
        db $F5
        db $3F
        db $A4
        db $FE
        db $03
        db $52
        db $7F
        db $08
        db $D4
        db $7F
        db $60
        db $50
        db $3F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $02
        db $00
        db $03
        db $08
        db $00
        db $18
        db $10
        db $00
        db $0C
        db $20
        db $00
        db $E0
        db $80
        db $06
        db $20
        db $00
        db $06
        db $08
        db $00
        db $0C
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $20
        db $00
        db $80
        db $10
        db $00
        db $20
        db $08
        db $00
        db $20
        db $04
        db $00
        db $0C
        db $01
        db $40
        db $04
        db $00
        db $40
        db $88
        db $01
        db $20
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $08
        db $0F
        db $FE
        db $10
        db $3C
        db $04
        db $23
        db $7F
        db $F8
        db $46
        db $F0
        db $D0
        db $F1
        db $BC
        db $3F
        db $CD
        db $FC
        db $24
        db $3F
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $10
        db $1B
        db $00
        db $88
        db $45
        db $3C
        db $14
        db $02
        db $00
        db $0A
        db $51
        db $08
        db $28
        db $04
        db $00
        db $C5
        db $00
        db $04
        db $06
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $0A
        db $10
        db $00
        db $14
        db $22
        db $8C
        db $21
        db $C0
        db $00
        db $40
        db $88
        db $10
        db $10
        db $20
        db $00
        db $83
        db $00
        db $21
        db $C0
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $10
        db $0C
        db $00
        db $08
        db $46
        db $30
        db $F4
        db $03
        db $00
        db $E2
        db $91
        db $0F
        db $88
        db $07
        db $00
        db $F9
        db $00
        db $FA
        db $03
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $11
        db $E0
        db $00
        db $21
        db $C4
        db $3C
        db $5F
        db $80
        db $00
        db $BF
        db $17
        db $E0
        db $2F
        db $C0
        db $01
        db $7E
        db $00
        db $5F
        db $C0
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $E8
        db $07
        db $00
        db $F4
        db $DF
        db $1F
        db $FA
        db $7F
        db $00
        db $FD
        db $E8
        db $07
        db $F4
        db $03
        db $80
        db $7E
        db $00
        db $FA
        db $7F
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $17
        db $E0
        db $00
        db $2F
        db $87
        db $F8
        db $5F
        db $FE
        db $00
        db $BF
        db $17
        db $E0
        db $2F
        db $C0
        db $01
        db $7E
        db $00
        db $5F
        db $FF
        db $80
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $E8
        db $07
        db $00
        db $F4
        db $FF
        db $0F
        db $FA
        db $7F
        db $00
        db $FD
        db $E8
        db $07
        db $F4
        db $03
        db $80
        db $7E
        db $00
        db $E4
        db $FF
        db $03
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $2F
        db $C0
        db $00
        db $5F
        db $FF
        db $E0
        db $BE
        db $04
        db $01
        db $7E
        db $2F
        db $C0
        db $5F
        db $80
        db $02
        db $FC
        db $00
        db $18
        db $1F
        db $E0
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $F4
        db $03
        db $00
        db $FA
        db $FF
        db $01
        db $FD
        db $3F
        db $80
        db $7E
        db $F4
        db $03
        db $FA
        db $01
        db $40
        db $3F
        db $00
        db $E0
        db $F7
        db $07
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $2E
        db $C0
        db $00
        db $5D
        db $BD
        db $00
        db $BB
        db $00
        db $01
        db $7E
        db $2F
        db $40
        db $5F
        db $80
        db $02
        db $FC
        db $00
        db $00
        db $2F
        db $E0
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $C4
        db $03
        db $00
        db $E2
        db $E1
        db $01
        db $F1
        db $00
        db $80
        db $6E
        db $84
        db $03
        db $BA
        db $01
        db $40
        db $37
        db $00
        db $00
        db $F4
        db $06
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $5F
        db $80
        db $00
        db $BF
        db $9F
        db $81
        db $7E
        db $00
        db $02
        db $1C
        db $5F
        db $80
        db $87
        db $00
        db $04
        db $38
        db $00
        db $00
        db $21
        db $E0
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $BA
        db $01
        db $00
        db $DD
        db $7A
        db $83
        db $6E
        db $00
        db $40
        db $3F
        db $7A
        db $01
        db $FD
        db $00
        db $A0
        db $1F
        db $00
        db $00
        db $F4
        db $03
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $47
        db $80
        db $00
        db $8F
        db $43
        db $C1
        db $1E
        db $00
        db $02
        db $EC
        db $83
        db $80
        db $BB
        db $00
        db $05
        db $D8
        db $00
        db $00
        db $5E
        db $C0
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FA
        db $FF
        db $0F
        db $FD
        db $F2
        db $83
        db $FE
        db $FF
        db $43
        db $FC
        db $FE
        db $E1
        db $F1
        db $07
        db $20
        db $1E
        db $80
        db $FF
        db $C1
        db $03
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $4F
        db $FF
        db $F1
        db $72
        db $2C
        db $22
        db $FF
        db $FF
        db $C5
        db $FF
        db $FD
        db $0B
        db $FF
        db $E0
        db $0B
        db $F0
        db $02
        db $FF
        db $FE
        db $80
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $04
        db $00
        db $86
        db $40
        db $04
        db $44
        db $00
        db $80
        db $21
        db $00
        db $40
        db $10
        db $00
        db $02
        db $10
        db $08
        db $40
        db $00
        db $80
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $18
        db $00
        db $21
        db $02
        db $20
        db $22
        db $00
        db $00
        db $84
        db $00
        db $0C
        db $08
        db $00
        db $40
        db $08
        db $10
        db $02
        db $00
        db $06
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $E0
        db $FF
        db $87
        db $7F
        db $FC
        db $C7
        db $FF
        db $FF
        db $E1
        db $FF
        db $0F
        db $F0
        db $FF
        db $03
        db $F0
        db $0F
        db $C0
        db $FF
        db $1F
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
