fontgfx:
fontsize equ 196
        db $00
        db $7C
        db $FC
        db $7C
        db $FC
        db $7E
        db $7E
        db $7C
        db $DE
        db $7E
        db $FE
        db $F6
        db $F8
        db $6C
        db $7C
        db $7C
        db $7C
        db $7C
        db $7C
        db $7C
        db $FE
        db $DE
        db $F6
        db $C6
        db $DE
        db $F6
        db $FE
        db $FF
        db $00
        db $6F
        db $6F
        db $6F
        db $6F
        db $0F
        db $0F
        db $63
        db $7B
        db $3C
        db $78
        db $6F
        db $1F
        db $7F
        db $7B
        db $7B
        db $6F
        db $7B
        db $6F
        db $6F
        db $3E
        db $7B
        db $6F
        db $63
        db $7B
        db $6F
        db $78
        db $FF
        db $00
        db $F6
        db $F6
        db $F0
        db $F6
        db $F0
        db $F0
        db $C0
        db $DE
        db $3C
        db $1E
        db $F6
        db $F8
        db $FE
        db $DE
        db $DE
        db $F6
        db $DE
        db $F6
        db $F0
        db $7C
        db $DE
        db $F6
        db $D6
        db $DE
        db $F6
        db $1E
        db $FF
        db $00
        db $7F
        db $3F
        db $0F
        db $6F
        db $3F
        db $3F
        db $7B
        db $7F
        db $3C
        db $78
        db $1F
        db $1F
        db $7F
        db $7B
        db $7B
        db $6F
        db $7B
        db $3F
        db $3E
        db $3E
        db $7B
        db $6F
        db $7F
        db $3E
        db $3E
        db $3E
        db $FF
        db $00
        db $F6
        db $F6
        db $F0
        db $F6
        db $F0
        db $F0
        db $DE
        db $DE
        db $3C
        db $DE
        db $F6
        db $F8
        db $D6
        db $DE
        db $DE
        db $FC
        db $DE
        db $F6
        db $1E
        db $7C
        db $DE
        db $F6
        db $FE
        db $DE
        db $38
        db $F0
        db $FF
        db $00
        db $6F
        db $6F
        db $6F
        db $6F
        db $0F
        db $0F
        db $73
        db $7B
        db $3C
        db $7B
        db $6F
        db $1F
        db $63
        db $7B
        db $7B
        db $0F
        db $7B
        db $6F
        db $7B
        db $3E
        db $7B
        db $3E
        db $7F
        db $7B
        db $1C
        db $0F
        db $FF
        db $00
        db $F6
        db $FC
        db $7C
        db $FC
        db $7E
        db $F0
        db $7C
        db $DE
        db $7E
        db $7C
        db $F6
        db $FE
        db $C6
        db $DE
        db $7C
        db $F0
        db $7C
        db $F6
        db $7C
        db $7C
        db $7C
        db $38
        db $6C
        db $DE
        db $38
        db $FE
        db $FF
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $FF
