greetingsgfx:
greetingssize equ 644
        db $00
        db $7F
        db $FF
        db $07
        db $FF
        db $C0
        db $0F
        db $FF
        db $FC
        db $1F
        db $FF
        db $F8
        db $7F
        db $FF
        db $F8
        db $07
        db $FF
        db $F0
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $80
        db $A1
        db $FE
        db $10
        db $D4
        db $0F
        db $08
        db $F5
        db $3F
        db $84
        db $FA
        db $1F
        db $02
        db $F5
        db $1F
        db $18
        db $D4
        db $0F
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $02
        db $00
        db $03
        db $08
        db $00
        db $18
        db $10
        db $00
        db $0C
        db $20
        db $00
        db $18
        db $80
        db $00
        db $18
        db $20
        db $00
        db $30
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $20
        db $00
        db $80
        db $10
        db $00
        db $20
        db $08
        db $00
        db $20
        db $04
        db $00
        db $10
        db $01
        db $00
        db $10
        db $62
        db $00
        db $08
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $08
        db $67
        db $FE
        db $10
        db $3C
        db $04
        db $23
        db $7F
        db $F8
        db $46
        db $FF
        db $F0
        db $FF
        db $37
        db $F0
        db $90
        db $FF
        db $E0
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $50
        db $10
        db $00
        db $88
        db $45
        db $3C
        db $14
        db $02
        db $00
        db $0A
        db $01
        db $00
        db $40
        db $31
        db $00
        db $81
        db $01
        db $00
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $08
        db $10
        db $00
        db $14
        db $22
        db $8C
        db $21
        db $C0
        db $00
        db $43
        db $80
        db $00
        db $02
        db $0C
        db $00
        db $87
        db $00
        db $00
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $90
        db $0F
        db $00
        db $08
        db $46
        db $30
        db $F4
        db $03
        db $00
        db $FA
        db $01
        db $00
        db $40
        db $3E
        db $80
        db $FE
        db $00
        db $00
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $17
        db $E0
        db $00
        db $21
        db $C4
        db $3C
        db $5F
        db $80
        db $00
        db $BF
        db $00
        db $00
        db $05
        db $F8
        db $01
        db $7F
        db $00
        db $00
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $E8
        db $FF
        db $3F
        db $F4
        db $DF
        db $1F
        db $FA
        db $7F
        db $00
        db $FD
        db $3F
        db $00
        db $A0
        db $1F
        db $80
        db $FE
        db $1F
        db $00
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $17
        db $FF
        db $FC
        db $2F
        db $87
        db $F8
        db $5F
        db $FE
        db $00
        db $BF
        db $FC
        db $00
        db $05
        db $F8
        db $01
        db $7F
        db $FE
        db $00
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $E8
        db $FB
        db $3F
        db $F4
        db $FF
        db $0F
        db $FA
        db $7F
        db $00
        db $FD
        db $3F
        db $00
        db $A0
        db $1F
        db $00
        db $F9
        db $FF
        db $00
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $2F
        db $81
        db $F8
        db $5F
        db $FF
        db $E0
        db $BE
        db $04
        db $01
        db $7C
        db $08
        db $00
        db $0B
        db $F0
        db $00
        db $60
        db $7F
        db $80
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $F4
        db $BF
        db $1F
        db $FA
        db $FF
        db $01
        db $FD
        db $3F
        db $80
        db $FE
        db $1F
        db $00
        db $D0
        db $0F
        db $00
        db $F8
        db $FD
        db $01
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $2F
        db $45
        db $E8
        db $5D
        db $BD
        db $00
        db $BB
        db $00
        db $01
        db $76
        db $00
        db $00
        db $0B
        db $F0
        db $00
        db $00
        db $BF
        db $80
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $84
        db $23
        db $1C
        db $E2
        db $E1
        db $01
        db $F1
        db $00
        db $80
        db $78
        db $00
        db $00
        db $D0
        db $0D
        db $00
        db $00
        db $BD
        db $01
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $5F
        db $89
        db $F0
        db $BF
        db $9F
        db $81
        db $7E
        db $00
        db $02
        db $FC
        db $00
        db $00
        db $10
        db $E0
        db $00
        db $00
        db $87
        db $80
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $7A
        db $D1
        db $0B
        db $DD
        db $7A
        db $83
        db $6E
        db $00
        db $40
        db $37
        db $00
        db $00
        db $E8
        db $07
        db $00
        db $00
        db $FD
        db $00
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $43
        db $88
        db $70
        db $8F
        db $43
        db $C1
        db $1E
        db $00
        db $02
        db $3C
        db $00
        db $00
        db $17
        db $60
        db $00
        db $01
        db $7B
        db $00
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FA
        db $CF
        db $0F
        db $FD
        db $F2
        db $83
        db $FE
        db $FF
        db $43
        db $FF
        db $FF
        db $01
        db $88
        db $07
        db $E0
        db $7F
        db $F0
        db $00
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $4F
        db $0F
        db $A1
        db $72
        db $2C
        db $22
        db $FF
        db $FF
        db $C5
        db $FF
        db $FF
        db $80
        db $2F
        db $C0
        db $0B
        db $FF
        db $FA
        db $00
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $04
        db $00
        db $84
        db $40
        db $04
        db $44
        db $00
        db $80
        db $21
        db $00
        db $C0
        db $00
        db $04
        db $02
        db $10
        db $00
        db $20
        db $00
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $18
        db $00
        db $21
        db $02
        db $20
        db $22
        db $00
        db $00
        db $84
        db $00
        db $01
        db $00
        db $20
        db $40
        db $08
        db $00
        db $18
        db $00
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $E0
        db $FF
        db $87
        db $7F
        db $FC
        db $C7
        db $FF
        db $FF
        db $E1
        db $FF
        db $FF
        db $00
        db $FC
        db $03
        db $F0
        db $FF
        db $07
        db $00
        db $00
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
