roadrunnergfx:
roadrunnersize equ 2800
        db $00
        db $00
        db $00
        db $00
        db $3C
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $0E
        db $80
        db $5F
        db $00
        db $F4
        db $1F
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $F8
        db $07
        db $FC
        db $01
        db $FF
        db $FE
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $80
        db $1F
        db $F8
        db $5F
        db $F0
        db $FF
        db $BF
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $01
        db $FC
        db $3F
        db $AC
        db $3F
        db $FF
        db $FE
        db $9F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $C0
        db $1F
        db $FE
        db $8A
        db $FF
        db $FF
        db $BF
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $03
        db $F4
        db $FE
        db $A7
        db $FF
        db $FF
        db $EA
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $E0
        db $9F
        db $BF
        db $F8
        db $FF
        db $FF
        db $AB
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $07
        db $F3
        db $FA
        db $7F
        db $FF
        db $FE
        db $A8
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $E0
        db $D7
        db $2F
        db $FF
        db $FF
        db $AB
        db $02
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $0F
        db $F3
        db $E9
        db $FF
        db $EA
        db $A8
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $F0
        db $E7
        db $CF
        db $FF
        db $2A
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $0F
        db $D7
        db $E7
        db $FA
        db $A0
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $F8
        db $E7
        db $F3
        db $2B
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $0F
        db $CF
        db $DF
        db $A8
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $F8
        db $F5
        db $FF
        db $02
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $1F
        db $CF
        db $FE
        db $80
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $F8
        db $F7
        db $3F
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $1F
        db $FF
        db $F8
        db $BE
        db $80
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $60
        db $FC
        db $FF
        db $DF
        db $FF
        db $BF
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $06
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $E8
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $E0
        db $FC
        db $FF
        db $FF
        db $FF
        db $FF
        db $7F
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $03
        db $3F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $C0
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $A0
        db $FC
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $0F
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $03
        db $BF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $F8
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $A0
        db $F9
        db $FF
        db $FF
        db $AA
        db $FF
        db $FF
        db $3F
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $02
        db $DF
        db $FF
        db $FF
        db $82
        db $AF
        db $FF
        db $FE
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $80
        db $FB
        db $FF
        db $FF
        db $1F
        db $AA
        db $FF
        db $FF
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $EF
        db $FF
        db $FF
        db $FF
        db $8A
        db $FF
        db $FF
        db $9F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $80
        db $EE
        db $FF
        db $FF
        db $FF
        db $8F
        db $FE
        db $FF
        db $FB
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $FF
        db $FF
        db $FF
        db $FF
        db $FE
        db $AF
        db $FF
        db $DF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $FE
        db $FF
        db $FF
        db $FF
        db $FF
        db $EA
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $2F
        db $FF
        db $FF
        db $FF
        db $FF
        db $AA
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $EA
        db $FF
        db $FF
        db $FA
        db $FF
        db $A3
        db $FE
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $2B
        db $FF
        db $FA
        db $AB
        db $FF
        db $E0
        db $BF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $A8
        db $FF
        db $2B
        db $A0
        db $FE
        db $0F
        db $FA
        db $FB
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $0B
        db $FF
        db $A8
        db $02
        db $BF
        db $F8
        db $2F
        db $DF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $A0
        db $FF
        db $02
        db $80
        db $FA
        db $1F
        db $F8
        db $FB
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $02
        db $FE
        db $80
        db $00
        db $AF
        db $FC
        db $0A
        db $9F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $80
        db $FF
        db $00
        db $00
        db $FA
        db $3F
        db $A8
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $FE
        db $80
        db $00
        db $2F
        db $FE
        db $0A
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $80
        db $FE
        db $00
        db $00
        db $E8
        db $7F
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $FE
        db $00
        db $00
        db $0F
        db $FF
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $FE
        db $00
        db $00
        db $E8
        db $FF
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $FE
        db $00
        db $00
        db $0B
        db $FF
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $80
        db $7E
        db $00
        db $00
        db $A0
        db $FF
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $02
        db $FE
        db $00
        db $00
        db $03
        db $FF
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $80
        db $7F
        db $00
        db $00
        db $A0
        db $BE
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $03
        db $FF
        db $00
        db $00
        db $02
        db $AA
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $E0
        db $7F
        db $00
        db $00
        db $80
        db $0A
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $0B
        db $FF
        db $00
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $E8
        db $FF
        db $00
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $2F
        db $87
        db $80
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $FA
        db $CC
        db $00
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $3F
        db $7A
        db $70
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $7A
        db $1E
        db $1F
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $BE
        db $FD
        db $F8
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $80
        db $3E
        db $3F
        db $3F
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $FD
        db $FE
        db $FC
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $80
        db $9E
        db $7F
        db $3F
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $F9
        db $FE
        db $FC
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $80
        db $9F
        db $7F
        db $7F
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $70
        db $7E
        db $1E
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $7C
        db $70
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $07
        db $E0
        db $3E
        db $0E
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $F0
        db $3F
        db $78
        db $60
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $3F
        db $FE
        db $1C
        db $86
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FE
        db $FF
        db $99
        db $67
        db $00
        db $02
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $07
        db $C3
        db $F0
        db $07
        db $90
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $3F
        db $8E
        db $FF
        db $FF
        db $FF
        db $0C
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $F9
        db $F8
        db $FF
        db $FF
        db $FE
        db $70
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $DF
        db $1F
        db $FE
        db $FF
        db $3F
        db $0F
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $7F
        db $F9
        db $3F
        db $FF
        db $F9
        db $E0
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FC
        db $9F
        db $F9
        db $FF
        db $CF
        db $07
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $1F
        db $F8
        db $EF
        db $FF
        db $E7
        db $C0
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $F0
        db $1F
        db $FE
        db $FF
        db $F3
        db $01
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $07
        db $FC
        db $3F
        db $FF
        db $9F
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $80
        db $3F
        db $F8
        db $7F
        db $3C
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $3C
        db $0F
        db $F8
        db $E0
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $70
        db $C0
        db $07
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $07
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $C0
        db $C1
        db $00
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $01
        db $C7
        db $00
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $7F
        db $00
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $3C
        db $00
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $54
        db $00
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $55
        db $00
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $54
        db $00
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $74
        db $00
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $5F
        db $00
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $F4
        db $00
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $1F
        db $00
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $FC
        db $00
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $1F
        db $80
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $F4
        db $00
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $1F
        db $80
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $F0
        db $01
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $17
        db $80
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $50
        db $01
        db $00
        db $00
        db $00
        db $00
        db $F8
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $00
        db $00
        db $05
        db $00
        db $00
        db $00
        db $00
        db $00
        db $1F
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
        db $FF
