/*
 * DBConnectionEdit.java
 *
 * Created on 26. März 2008, 10:39
 */

package de.malban.jdbc;

import de.malban.config.Configuration;
import de.malban.gui.components.ModalInternalFrame;
import de.malban.gui.dialogs.InternalFrameFileChoser;
import de.malban.gui.dialogs.ShowInfoDialog;
import de.malban.jdbc.DBConnectionData;
import de.malban.util.Utility;
import javax.swing.*;
import java.sql.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.io.File;
import java.util.*;
//import javafx.stage.FileChooser;
import static javax.swing.JFileChooser.DIRECTORIES_ONLY;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 * A GUI Class to create and change DBConnctionData
 * Does itself not keep DBConnectionData - it refers internally to a DBConnectionDataPool as
 * the Main program and requests and sets Data to that class.
 * @author  A104032
 */
public class DBConnectionEdit extends JPanel {

    private DBConnectionDataPool mConnectionPool;
    private int mInSetting =0;
    ModalInternalFrame modal=null;
    
    public static void showDBConnectionEditDialog()
    {
        Configuration C = Configuration.getConfiguration();
        if (C.getMainFrame() == null) {
            return;
        }
        JFrame frame = Configuration.getConfiguration().getMainFrame();
        DBConnectionEdit dialog = new DBConnectionEdit();
        

    
        dialog.modal = new ModalInternalFrame("DB Connection", frame.getRootPane(), frame, dialog, dialog.jButtonSave);

        dialog.modal.setResizable(true);
        
        dialog.modal.setVisible(true);        
    }
    /** Creates new form DBConnectionEdit */
    private DBConnectionEdit() 
    {
        initComponents();
        
        jLabelPort1.setVisible(false);
        jTextFieldDir.setVisible(false);
        jButtonFileSelect1.setVisible(false);

        mConnectionPool = PoolFactory.POOL.getConnectionPool();
        setVisible(true);
    }
    
    private void setFields(DBConnectionData c)
    {
        if (c==null)
        {
            jTextFieldDBName.setText("");
            jTextFieldName.setText("");
            jTextFieldPassword.setText("");
            jComboBoxType1.setSelectedIndex(-1);
            jTextFieldServer.setText("");
            jTextFieldUser.setText("");
            jTextFieldHost.setText("");
            jTextFieldPort.setText("");
            jTextFieldClass.setText("");
            jTextFieldURL.setText("");
            setDriverStatus();
            return;
        }
        jTextFieldDBName.setText(c.mDBName);
        jTextFieldName.setText(c.mName);
        jTextFieldPassword.setText(c.mPasswd);
        jComboBoxType1.setSelectedItem(c.mType);
        jTextFieldServer.setText(c.mServer);
        jTextFieldUser.setText(c.mUser);
        jTextFieldHost.setText(c.mHost);
        jTextFieldPort.setText(c.mPort);
        jTextFieldURL.setText(c.mURL);
        jTextFieldClass.setText(c.mClass);
        setDriverStatus();
    }
    
    @Override public void setVisible(boolean b)
    {
        if (b)
        {
            Collection<DBConnectionData> col = mConnectionPool.getHashMap().values();
            Iterator<DBConnectionData> iter = col.iterator();
            int i = 0;
            mInSetting++;
            jComboBoxConnection.removeAllItems();
            while (iter.hasNext())
            {
                DBConnectionData item = (DBConnectionData) iter.next();
                jComboBoxConnection.addItem(item);

                if (i==0)
                {
                    jComboBoxConnection.setSelectedIndex(0);
                    setFields((DBConnectionData) item);
                }
                i++;
            }
            mInSetting--;

            jLabelResult.setText("");
        }
        super.setVisible(b);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelType = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabelUser = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jLabelDBName = new javax.swing.JLabel();
        jTextFieldDBName = new javax.swing.JTextField();
        jTextFieldServer = new javax.swing.JTextField();
        jLabelServer = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jButtonNew = new javax.swing.JButton();
        jComboBoxConnection = new javax.swing.JComboBox();
        jLabelConnection = new javax.swing.JLabel();
        jButtonTest = new javax.swing.JButton();
        jTextFieldHost = new javax.swing.JTextField();
        jLabelHost = new javax.swing.JLabel();
        jLabelPort = new javax.swing.JLabel();
        jTextFieldPort = new javax.swing.JTextField();
        jLabelResult = new javax.swing.JLabel();
        jComboBoxType1 = new javax.swing.JComboBox();
        jLabelisTested = new javax.swing.JLabel();
        jLabelConnectionsString = new javax.swing.JLabel();
        jLabelStringExample = new javax.swing.JLabel();
        jTextFieldExample = new javax.swing.JTextField();
        jTextFieldCurrent = new javax.swing.JTextField();
        jLabelURL = new javax.swing.JLabel();
        jTextFieldURL = new javax.swing.JTextField();
        jButtonHelp = new javax.swing.JButton();
        jLabelClass = new javax.swing.JLabel();
        jTextFieldClass = new javax.swing.JTextField();
        jTextFieldDir = new javax.swing.JTextField();
        jLabelPort1 = new javax.swing.JLabel();
        jButtonFileSelect1 = new javax.swing.JButton();

        jLabelName.setText("Name"); // NOI18N

        jLabelType.setText("Type"); // NOI18N

        jLabelUser.setText("User"); // NOI18N

        jLabelPassword.setText("Password"); // NOI18N

        jLabelDBName.setText("DBName"); // NOI18N

        jLabelServer.setText("Server/Instanz"); // NOI18N

        jButtonSave.setText("Accept"); // NOI18N
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonNew.setLabel("New"); // NOI18N
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jComboBoxConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConnectionActionPerformed(evt);
            }
        });

        jLabelConnection.setText("Connection"); // NOI18N

        jButtonTest.setLabel("Test"); // NOI18N
        jButtonTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestActionPerformed(evt);
            }
        });

        jTextFieldHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHostActionPerformed(evt);
            }
        });

        jLabelHost.setText("Host"); // NOI18N

        jLabelPort.setText("Port"); // NOI18N

        jLabelResult.setText("result "); // NOI18N

        jComboBoxType1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Oracle", "MySQL", "Derby (Java DB)", "Informix", "Postgre", "MSSQL", "Generic PW", "Generic Total" }));
        jComboBoxType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxType1ActionPerformed(evt);
            }
        });

        jLabelisTested.setText("test"); // NOI18N

        jLabelConnectionsString.setText("Current"); // NOI18N

        jLabelStringExample.setText("Example"); // NOI18N

        jTextFieldExample.setEditable(false);

        jTextFieldCurrent.setEditable(false);

        jLabelURL.setText("URL"); // NOI18N

        jButtonHelp.setText("Type Help");
        jButtonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpActionPerformed(evt);
            }
        });

        jLabelClass.setText("Class");

        jTextFieldClass.setEnabled(false);

        jTextFieldDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDirActionPerformed(evt);
            }
        });

        jLabelPort1.setText("Dir"); // NOI18N

        jButtonFileSelect1.setText("...");
        jButtonFileSelect1.setToolTipText("Chose directory");
        jButtonFileSelect1.setMargin(new java.awt.Insets(0, 1, 0, -1));
        jButtonFileSelect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFileSelect1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelPassword)
                                .addComponent(jLabelUser)
                                .addComponent(jLabelServer)
                                .addComponent(jLabelURL)
                                .addComponent(jLabelStringExample)
                                .addComponent(jLabelConnectionsString))
                            .addGap(18, 18, 18))
                        .addComponent(jLabelConnection))
                    .addComponent(jLabelName)
                    .addComponent(jLabelType)
                    .addComponent(jLabelHost)
                    .addComponent(jLabelPort)
                    .addComponent(jLabelDBName)
                    .addComponent(jLabelClass))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCurrent, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                            .addComponent(jTextFieldURL, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                            .addComponent(jTextFieldExample, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                            .addComponent(jLabelResult, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTest)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNew)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSave)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUser, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldServer, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPort, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldHost, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxType1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDBName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldClass, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jComboBoxConnection, javax.swing.GroupLayout.Alignment.LEADING, 0, 185, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonHelp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelisTested))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPort1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldDir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonFileSelect1))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConnection)
                    .addComponent(jComboBoxConnection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelType)
                    .addComponent(jButtonHelp)
                    .addComponent(jLabelisTested))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPort))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDBName)
                    .addComponent(jTextFieldDBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPort1)
                    .addComponent(jTextFieldDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFileSelect1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelServer)
                    .addComponent(jTextFieldServer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUser)
                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelURL)
                    .addComponent(jTextFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldExample, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStringExample))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConnectionsString))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTest)
                    .addComponent(jButtonNew)
                    .addComponent(jButtonSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelResult)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        DBConnectionData c = new DBConnectionData();
        mConnectionPool.put(c.mName, c);
        mInSetting++;
        jComboBoxConnection.addItem(c);
        jComboBoxConnection.setSelectedIndex(mConnectionPool.getSize()-1);
        mInSetting--;
        setFields(c);
        jLabelResult.setText("");
        
            
}//GEN-LAST:event_jButtonNewActionPerformed

    private void jComboBoxConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConnectionActionPerformed
       
        if (mInSetting>0) return;
        DBConnectionData c = (DBConnectionData) jComboBoxConnection.getSelectedItem();
        setFields(c);
        jLabelResult.setText("");
        
}//GEN-LAST:event_jComboBoxConnectionActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        int index = jComboBoxConnection.getSelectedIndex();
        DBConnectionData c = (DBConnectionData) mConnectionPool.get(jTextFieldName.getText());
        if (c==null)
        {
            c = new DBConnectionData();
        }
    
        c.mDBName =jTextFieldDBName.getText();
        c.mName =jTextFieldName.getText();
        c.mPasswd =jTextFieldPassword.getText();
        c.mType =jComboBoxType1.getSelectedItem().toString();
        c.mServer =jTextFieldServer.getText();
        c.mUser =jTextFieldUser.getText();
        c.mHost =jTextFieldHost.getText();
        c.mPort =jTextFieldPort.getText();
        c.mURL =jTextFieldURL.getText();
        c.mClass =jTextFieldClass.getText();
        
        mConnectionPool.put(c.mName, c);
        mConnectionPool.save();

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestActionPerformed
       
        DBConnectionData c = new DBConnectionData();
        c.mDBName =jTextFieldDBName.getText();
        c.mName =jTextFieldName.getText();
        c.mPasswd =jTextFieldPassword.getText();
        c.mType =jComboBoxType1.getSelectedItem().toString();
        c.mServer =jTextFieldServer.getText();
        c.mUser =jTextFieldUser.getText();
        c.mHost =jTextFieldHost.getText();
        c.mPort =jTextFieldPort.getText();
        c.mURL =jTextFieldURL.getText();
        c.mClass =jTextFieldClass.getText();

        String sel = "";
        if (jComboBoxType1.getSelectedItem() == null) 
            sel = new String();
        else
            sel = jComboBoxType1.getSelectedItem().toString();
        if ("Derby (Java DB)".equalsIgnoreCase(sel))
        
        {
            if (jTextFieldDir.getText().trim().length()>0)
            {
                c.mDBName = jTextFieldDir.getText()+ File.pathSeparator+ c.mDBName;
            }
        }
        
        
        jTextFieldCurrent.setText(c.getConnectionString());
        jLabelResult.setText("");


        c.openConnection();
        Connection dbc = c.getConnection();
        if (dbc != null)
        {
            jLabelResult.setForeground(Color.GREEN);
            jLabelResult.setText("OK!");
            c.closeConnection();
        }
        else
        {
            jLabelResult.setForeground(Color.RED);
            jLabelResult.setText("ERROR! :"+ "\n"+c.mLastException.toString());
            
            System.out.println(Utility.getStackTrace(c.mLastException));
        }
    }//GEN-LAST:event_jButtonTestActionPerformed

    private void jTextFieldHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHostActionPerformed
       
}//GEN-LAST:event_jTextFieldHostActionPerformed

    private void jComboBoxType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxType1ActionPerformed
        setDriverStatus(); 
        if (jComboBoxType1.getSelectedItem() != null)
        {
            String example = DBConnectionData.getExample(jComboBoxType1.getSelectedItem().toString());
            jTextFieldExample.setText(example);
        }
        else
        {
            jTextFieldExample.setText("");
        }
        jTextFieldCurrent.setText("");
        jLabelResult.setText("");

    }//GEN-LAST:event_jComboBoxType1ActionPerformed

    private void korrektVisibility()
    {
        String sel;
        jLabelPort1.setVisible(false);
        jTextFieldDir.setVisible(false);
        jButtonFileSelect1.setVisible(false);
        
        if (jComboBoxType1.getSelectedItem() == null) 
            sel = new String();
        else
            sel = jComboBoxType1.getSelectedItem().toString();
        
        if ("Derby (Java DB)".equalsIgnoreCase(sel))
        {
            jTextFieldServer.setEditable(false);
            jTextFieldHost.setEditable(false);
            jTextFieldPort.setEditable(false);
            jTextFieldClass.setEditable(false);

            jTextFieldServer.setEnabled(false);
            jTextFieldHost.setEnabled(false);
            jTextFieldPort.setEnabled(false);
            jTextFieldClass.setEnabled(false);
            
            jLabelPort1.setVisible(true);
            jTextFieldDir.setVisible(true);
            jButtonFileSelect1.setVisible(true);
        }
        
        else if ("generic total".equalsIgnoreCase(sel))
        {
            jTextFieldDBName.setEditable(false);
            jTextFieldPassword.setEditable(false);
            jTextFieldServer.setEditable(false);
            jTextFieldUser.setEditable(false);
            jTextFieldHost.setEditable(false);
            jTextFieldPort.setEditable(false);
            jTextFieldClass.setEditable(true);

            jTextFieldDBName.setEnabled(false);
            jTextFieldPassword.setEnabled(false);
            jTextFieldServer.setEnabled(false);
            jTextFieldUser.setEnabled(false);
            jTextFieldHost.setEnabled(false);
            jTextFieldPort.setEnabled(false);
            jTextFieldClass.setEnabled(true);
        }
        else if ("generic pw".equalsIgnoreCase(sel))
        {
            jTextFieldDBName.setEditable(false);
            jTextFieldPassword.setEditable(true);
            jTextFieldServer.setEditable(false);
            jTextFieldUser.setEditable(true);
            jTextFieldHost.setEditable(false);
            jTextFieldPort.setEditable(false);
            jTextFieldClass.setEditable(true);

            jTextFieldDBName.setEnabled(false);
            jTextFieldPassword.setEnabled(true);
            jTextFieldServer.setEnabled(false);
            jTextFieldUser.setEnabled(true);
            jTextFieldHost.setEnabled(false);
            jTextFieldPort.setEnabled(false);
            jTextFieldClass.setEnabled(true);
        }
        else 
        {
            jTextFieldDBName.setEditable(true);
            jTextFieldPassword.setEditable(true);
            jTextFieldServer.setEditable(true);
            jTextFieldUser.setEditable(true);
            jTextFieldHost.setEditable(true);
            jTextFieldPort.setEditable(true);
            jTextFieldClass.setEditable(false);

            jTextFieldDBName.setEnabled(true);
            jTextFieldPassword.setEnabled(true);
            jTextFieldServer.setEnabled(true);
            jTextFieldUser.setEnabled(true);
            jTextFieldHost.setEnabled(true);
            jTextFieldPort.setEnabled(true);
            jTextFieldClass.setEnabled(false);
        }
    }
    private void jButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpActionPerformed
        DBConnectionData c = (DBConnectionData) jComboBoxConnection.getSelectedItem();
        
        if (c!=null)
        {
            c.mType =jComboBoxType1.getSelectedItem().toString();

            ShowInfoDialog.showInfoDialog("Hilfe", c.getHelpText());
        }
        
    }//GEN-LAST:event_jButtonHelpActionPerformed

    private void jTextFieldDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDirActionPerformed
       
    }//GEN-LAST:event_jTextFieldDirActionPerformed

    private void jButtonFileSelect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFileSelect1ActionPerformed

        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new java.io.File("."));
        fc.setFileSelectionMode(DIRECTORIES_ONLY);
        int r = fc.showOpenDialog(Configuration.getConfiguration().getMainFrame());
        if (r != InternalFrameFileChoser.APPROVE_OPTION) {
            return;
        }
        String name = fc.getSelectedFile().getName();
        jTextFieldDir.setText(name);
    }//GEN-LAST:event_jButtonFileSelect1ActionPerformed

    private void setDriverStatus()
    {
        jLabelisTested.setText("");
        if (jComboBoxType1.getSelectedItem() == null) return;
        String sel = jComboBoxType1.getSelectedItem().toString();
        if (sel.equalsIgnoreCase("postgre"))
        {
            jLabelisTested.setText("Driver untested");
        }
        if (sel.equalsIgnoreCase("Generic PW"))
        {
            jLabelisTested.setText("Own Risc!");
        }
        if (sel.equalsIgnoreCase("Generic Total"))
        {
            jLabelisTested.setText("Own Risc!");
        }
        korrektVisibility();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFileSelect1;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonTest;
    private javax.swing.JComboBox jComboBoxConnection;
    private javax.swing.JComboBox jComboBoxType1;
    private javax.swing.JLabel jLabelClass;
    private javax.swing.JLabel jLabelConnection;
    private javax.swing.JLabel jLabelConnectionsString;
    private javax.swing.JLabel jLabelDBName;
    private javax.swing.JLabel jLabelHost;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JLabel jLabelPort1;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JLabel jLabelServer;
    private javax.swing.JLabel jLabelStringExample;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelURL;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelisTested;
    public javax.swing.JTextField jTextFieldClass;
    public javax.swing.JTextField jTextFieldCurrent;
    public javax.swing.JTextField jTextFieldDBName;
    private javax.swing.JTextField jTextFieldDir;
    public javax.swing.JTextField jTextFieldExample;
    private javax.swing.JTextField jTextFieldHost;
    public javax.swing.JTextField jTextFieldName;
    public javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldPort;
    public javax.swing.JTextField jTextFieldServer;
    public javax.swing.JTextField jTextFieldURL;
    public javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
    
}
