/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.malban.gui;

import java.util.Vector;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JInternalFrame;

/**
 *
 * @author salchr
 */
public class WindowManagerJPanel extends javax.swing.JPanel {
    CSAMainFrame main;
    /**
     * Creates new form WindowManagerJPanel
     */
    public WindowManagerJPanel(CSAMainFrame m) {
        initComponents();
        main = m;
        init();
    }

    void init()
    {
        jPanel1.removeAll();
        
        jScrollPane1.setBackground(new java.awt.Color(200, 200, 255,255));
        jPanel1.setBackground(new java.awt.Color(200, 200, 255,255));
        jScrollPane1.setBorder(null);
        int x = 1;
        int y=2;
        for (int i=0; i<main.mFrames.size(); i++)
        {
            JInternalFrame f = main.mFrames.elementAt(i);
            javax.swing.JButton jButton = new javax.swing.JButton();
            jButton.setText(f.getTitle());
            jButton.setBounds(x, y, 154, 23);
            y+= 23+2;
            jPanel1.add(jButton);
        }
        sizeY = y;
        ((JButton)jPanel1.getComponent(selected)).setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
    }
    int sizeY =0;
    int selected = 0;
    public int getSizeY()
    {
        return sizeY;
    }
    public int getSel()
    {
        return selected;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setLayout(null);

        jButton1.setText("jButton1");
        jButton1.setBorder(null);
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 10, 140, 20);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    public void doTab()
    {
        
        int max = jPanel1.getComponentCount();
        if (max == 0) return;
        ((JButton)jPanel1.getComponent(selected)).setBorder(null);
        selected = (selected+1)%max;
        ((JButton)jPanel1.getComponent(selected)).setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));

        repaint();
    }
}
