/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.malban.vide.vecx.panels;

import de.malban.gui.dialogs.InternalColorChooserDialog;
import de.malban.vide.vecx.devices.Imager3dDevice;
import de.malban.vide.vecx.devices.WheelData;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author malban
 */
public class OneWheelColorPanel extends javax.swing.JPanel {

    int colorNo = -1;
    WheelData wheel=null;
    WheelEdit editor = null;
    private int mClassSetting=0;
    /**
     * Creates new form OneWheelColorPanel
     */
    public OneWheelColorPanel(WheelData w, int c, WheelEdit e) {
        mClassSetting++;
        wheel = w;
        colorNo = c;
        editor = e;
        initComponents();
        update();
        mClassSetting--;
    }

    public void update()
    {
        mClassSetting++;
        
        // since black is never used here - we can "savely" use color-1
        int min = (int)wheel.startAngle[colorNo-1];
        if (colorNo==1)
        {
            wheel.startAngle[colorNo] = 180;
            min = 180; // first color always starts at 180
        }
        
        jSlider4.setMinimum((int)wheel.startAngle[colorNo-1]);
        jSlider4.setValue((int)wheel.startAngle[colorNo]);
        jTextField47.setText(""+(int)wheel.startAngle[colorNo]);
        jTextField47.setBackground(wheel.colors[colorNo]);
        jSlider4.setEnabled(colorNo!=1); // first COLOR always starts at 180

        double right = wheel.startAngle[colorNo]+90;
        double left = wheel.startAngle[colorNo]+90+180;

        setCycle(right, jLabelRight, wheel);      
        setCycle(left, jLabelLeft, wheel);      
        
        mClassSetting--;
    }
    public static void setCycle(double angle, JLabel label, WheelData wheel)
    {
        
        double angleOffset = ((Imager3dDevice.indexAngleWidth+Imager3dDevice.photoReceiverAngleStart+(360-wheel.indexAngle))%360);
        angle += angleOffset;
        
        angle = angle %360;
//////////
        double anglePerCycle = 360.0 / (1500000.0/wheel.defaultFrequency);
//////////        
        
        
        double cycles = angle / anglePerCycle;
        label.setText("0x"+String.format("%04X", ((int)cycles)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel52 = new javax.swing.JLabel();
        jTextField47 = new javax.swing.JTextField();
        jSlider4 = new javax.swing.JSlider();
        jButtonColor = new javax.swing.JButton();
        jButtonColor1 = new javax.swing.JButton();
        jLabelRight = new javax.swing.JLabel();
        jLabelLeft = new javax.swing.JLabel();

        jLabel52.setText("angle");

        jSlider4.setMajorTickSpacing(10);
        jSlider4.setMaximum(360);
        jSlider4.setMinimum(180);
        jSlider4.setMinorTickSpacing(1);
        jSlider4.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider4.setPaintTicks(true);
        jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider4StateChanged(evt);
            }
        });

        jButtonColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/malban/vide/images/color_swatch.png"))); // NOI18N
        jButtonColor.setToolTipText("choose color");
        jButtonColor.setMargin(new java.awt.Insets(0, 0, 0, -1));
        jButtonColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColorActionPerformed(evt);
            }
        });

        jButtonColor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/malban/vide/images/delete.png"))); // NOI18N
        jButtonColor1.setToolTipText("delete color");
        jButtonColor1.setMargin(new java.awt.Insets(0, 0, 0, -1));
        jButtonColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor1ActionPerformed(evt);
            }
        });

        jLabelRight.setText("0x0000");
        jLabelRight.setToolTipText("start at cycles [relation to index whole]");

        jLabelLeft.setText("0x0000");
        jLabelLeft.setToolTipText("start at cycles [relation to index whole]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSlider4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField47, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonColor, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelRight)
                    .addComponent(jLabelLeft))
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel52)
                .addGap(4, 4, 4)
                .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonColor1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRight)
                .addGap(4, 4, 4)
                .addComponent(jLabelLeft)
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider4StateChanged
        if (wheel==null) return;
        if (mClassSetting > 1) return;
        wheel.startAngle[colorNo] = jSlider4.getValue();
        jTextField47.setText(""+(int)wheel.startAngle[colorNo]);
        editor.colorChanged(colorNo);
    }//GEN-LAST:event_jSlider4StateChanged

    private void jButtonColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorActionPerformed
        Color c = InternalColorChooserDialog.showDialog("Color");
        if (c == null) return;
        wheel.colors[colorNo] = c;
        jTextField47.setBackground(wheel.colors[colorNo]);
        editor.colorChanged(colorNo);
    }//GEN-LAST:event_jButtonColorActionPerformed

    private void jButtonColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor1ActionPerformed
        editor.removeSection(colorNo);
    }//GEN-LAST:event_jButtonColor1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonColor;
    private javax.swing.JButton jButtonColor1;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabelLeft;
    private javax.swing.JLabel jLabelRight;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JTextField jTextField47;
    // End of variables declaration//GEN-END:variables
}
