/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.malban.gui.dialogs;

import de.malban.config.Configuration;
import de.malban.gui.components.ModalInternalFrame;
import de.malban.vide.veccy.VectorListFileChoserJPanel;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author malban
 */
public class FontChooserPanel extends javax.swing.JPanel {

    /**
     * Creates new form FontChooser
     */
    public FontChooserPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fontChooserComponent1 = new de.malban.gui.dialogs.FontChooserComponent();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        jButtonOk.setText("select");
        jButtonOk.setName("create"); // NOI18N

        jButtonCancel.setText("cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(fontChooserComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fontChooserComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCancel)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.malban.gui.dialogs.FontChooserComponent fontChooserComponent1;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    // End of variables declaration//GEN-END:variables
    JInternalFrame modelDialog;
    public static de.malban.gui.dialogs.FontChooserComponent showFontChoserDialog(String title, SimpleAttributeSet style, boolean enableSize)
    {
        JFrame frame = Configuration.getConfiguration().getMainFrame();
        FontChooserPanel panel = new FontChooserPanel();
        panel.fontChooserComponent1.setSelectedFontFamily(StyleConstants.getFontFamily(style));
        panel.fontChooserComponent1.setSelectedFontSize(StyleConstants.getFontSize(style));
        panel.fontChooserComponent1.setSelectedFontStyle( (StyleConstants.isBold(style)?Font.BOLD:0)+(StyleConstants.isItalic(style)?Font.ITALIC:0));
        panel.fontChooserComponent1.setSizeEnabled(enableSize);
        
        
        ArrayList<JButton> eb= new ArrayList<JButton>();
        eb.add(panel.jButtonOk);
        eb.add(panel.jButtonCancel);
        ModalInternalFrame modal = new ModalInternalFrame(title, frame.getRootPane(), frame, panel,null, null , eb);
        
        modal.setResizable(true);
        panel.modelDialog = modal;
        modal.setVisible(true);

        String result = modal.getNamedExit();
        if ((result.equals("create")) || (modal.isManualOkExit()))
        {
            return panel.fontChooserComponent1;
        }
        
        return null;
    }   

}
