/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GetStringDialog.java
 *
 * Created on 11.02.2010, 20:22:35
 */

package de.malban.gui.dialogs;

import de.malban.config.Configuration;
import de.malban.gui.components.CSAInternalFrame;
import de.malban.gui.components.ModalInternalFrame;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Malban
 */
public class ShowInfoDialog extends javax.swing.JPanel {

    JInternalFrame modal=null;
    /** Creates new form GetStringDialog */
    public ShowInfoDialog() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("Ok");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("i");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel1.setText("The images were saved!\n");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (modal==null) return;
        modal.setVisible(false);   
        modal=null;
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    public void setText(String text)
    {
        jLabel1.setText(text);
    }
    
    public static void showInfoDialog(String text)
    {
        Configuration C = Configuration.getConfiguration();
        if (C.getMainFrame() == null) {
            return;
        }
        JFrame frame = Configuration.getConfiguration().getMainFrame();
        ShowInfoDialog si = new ShowInfoDialog();
        si.setText(text);
        
        si.modal = new ModalInternalFrame("Info", frame.getRootPane(), frame, si);
        si.modal.setVisible(true);        
    }
    
    public static void showInfoDialog(String titel, String message)
    {
        Configuration C = Configuration.getConfiguration();
        if (C.getMainFrame() == null) {
            return;
        }
        JFrame frame = Configuration.getConfiguration().getMainFrame();
        ShowInfoDialog si = new ShowInfoDialog();
        si.setText(message);
        
        si.modal = new ModalInternalFrame(titel, frame.getRootPane(), frame, si);
        si.modal.setVisible(true);        
    }
    public void setButtonVisible(boolean b)
    {
        jButton1.setVisible(b);
    }
    
}
