gfx_bresen:
        db $00
        db $00
        db $00
        db $00
        db $04
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $03
        db $C0
        db $00
        db $0F
        db $80
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $07
        db $C0
        db $00
        db $0F
        db $80
        db $00
        db $11
        db $FF
        db $E0
        db $FF
        db $F0
        db $0F
        db $F8
        db $07
        db $FC
        db $03
        db $FE
        db $0F
        db $FF
        db $07
        db $E3
        db $E0
        db $7F
        db $C1
        db $FC
        db $7F
        db $A0
        db $00
        db $07
        db $C0
        db $00
        db $0F
        db $E0
        db $00
        db $41
        db $FF
        db $B0
        db $FF
        db $D8
        db $3F
        db $EC
        db $1F
        db $F6
        db $0F
        db $FB
        db $0F
        db $FD
        db $87
        db $E2
        db $21
        db $FF
        db $61
        db $FE
        db $F8
        db $80
        db $00
        db $19
        db $C0
        db $00
        db $70
        db $60
        db $00
        db $41
        db $F0
        db $D8
        db $F8
        db $6C
        db $7C
        db $36
        db $3E
        db $1F
        db $1F
        db $0D
        db $8F
        db $86
        db $C7
        db $C3
        db $63
        db $E1
        db $B1
        db $FB
        db $FD
        db $80
        db $00
        db $19
        db $C0
        db $00
        db $70
        db $60
        db $01
        db $03
        db $E1
        db $91
        db $F0
        db $C8
        db $F8
        db $74
        db $7C
        db $00
        db $3E
        db $1D
        db $1F
        db $0E
        db $8F
        db $87
        db $47
        db $C3
        db $A3
        db $EF
        db $DD
        db $10
        db $00
        db $60
        db $38
        db $00
        db $70
        db $60
        db $03
        db $03
        db $E1
        db $B1
        db $F0
        db $D8
        db $F8
        db $64
        db $7C
        db $00
        db $3E
        db $19
        db $1F
        db $0C
        db $8F
        db $87
        db $47
        db $C3
        db $23
        db $E5
        db $9D
        db $08
        db $00
        db $60
        db $38
        db $03
        db $80
        db $18
        db $06
        db $03
        db $FF
        db $61
        db $FF
        db $B0
        db $FF
        db $CC
        db $6F
        db $F0
        db $3F
        db $F3
        db $1F
        db $0D
        db $8F
        db $FE
        db $C7
        db $FF
        db $63
        db $E7
        db $1B
        db $08
        db $01
        db $81
        db $38
        db $03
        db $88
        db $18
        db $0C
        db $07
        db $FF
        db $C3
        db $FF
        db $E1
        db $FF
        db $F8
        db $3F
        db $D8
        db $7F
        db $FE
        db $3E
        db $1D
        db $1F
        db $FE
        db $8F
        db $FF
        db $47
        db $C2
        db $3A
        db $04
        db $01
        db $80
        db $38
        db $03
        db $80
        db $18
        db $18
        db $07
        db $C3
        db $E3
        db $E1
        db $F1
        db $B0
        db $00
        db $00
        db $6C
        db $6C
        db $00
        db $3E
        db $1F
        db $1F
        db $0F
        db $8F
        db $87
        db $C7
        db $C0
        db $3E
        db $06
        db $06
        db $00
        db $B8
        db $1C
        db $20
        db $18
        db $30
        db $05
        db $C3
        db $E2
        db $E1
        db $F1
        db $F0
        db $00
        db $00
        db $6C
        db $7C
        db $00
        db $2E
        db $1F
        db $17
        db $0F
        db $8B
        db $87
        db $C5
        db $C0
        db $3E
        db $02
        db $06
        db $01
        db $07
        db $1C
        db $10
        db $06
        db $60
        db $0D
        db $87
        db $C6
        db $C3
        db $E3
        db $61
        db $F1
        db $F0
        db $F8
        db $D8
        db $7C
        db $6C
        db $3E
        db $36
        db $1F
        db $1B
        db $0F
        db $8D
        db $80
        db $7C
        db $03
        db $18
        db $00
        db $47
        db $1C
        db $80
        db $06
        db $C0
        db $08
        db $FF
        db $C4
        db $43
        db $E1
        db $BF
        db $F0
        db $DF
        db $F8
        db $6F
        db $FC
        db $44
        db $3E
        db $22
        db $1F
        db $11
        db $0F
        db $88
        db $80
        db $7C
        db $01
        db $18
        db $00
        db $A7
        db $E1
        db $40
        db $07
        db $80
        db $0F
        db $FF
        db $07
        db $C3
        db $E0
        db $FF
        db $C0
        db $7F
        db $E0
        db $3F
        db $F0
        db $7C
        db $3E
        db $3E
        db $1F
        db $1F
        db $0F
        db $8F
        db $80
        db $7C
        db $01
        db $E0
        db $00
        db $47
        db $E2
        db $80
        db $07
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $E0
        db $00
        db $A7
        db $E5
        db $20
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $00
        db $80
        db $00
        db $50
