/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templatesƒ
 * and open the template in the editor.
 */
package de.malban.vide.dissy;

import de.malban.config.Configuration;
import de.malban.gui.Stateable;
import de.malban.gui.Windowable;
import de.malban.gui.components.CSAView;
import de.malban.gui.dialogs.InternalFrameFileChoser;
import de.malban.util.syntax.Syntax.TokenStyles;
import de.malban.vide.vecx.Updatable;
import java.awt.Color;
import java.awt.Component;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.Serializable;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.JScrollBar;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author malban
 */
public class CompareDissiPanel extends javax.swing.JPanel  implements
        Windowable, Stateable, Updatable{
    public boolean isLoadSettings() { return true; }

    public static final String MESSAGE_INFO = "body";
    public static final String MESSAGE_WARN = "endtag";
    public static final String MESSAGE_ERR = "error";
    
    private CSAView mParent = null;
    private javax.swing.JMenuItem mParentMenuItem = null;
    private int mClassSetting=0;
    MemoryInformationTableModel model=null;
    DASM6809 dasm = new DASM6809();
    MemoryInformationTableModel model1=null;
    DASM6809 dasm1 = new DASM6809();
    boolean init = false;
    boolean init1 = false;
    JTable  popupSource = null;


    @Override
    public void closing()
    {
        deinit();
    }
    @Override
    public void setParentWindow(CSAView jpv)
    {
        mParent = jpv;
    }
    @Override
    public void setMenuItem(javax.swing.JMenuItem item)
    {
        mParentMenuItem = item;
        mParentMenuItem.setText("Dissi");
    }
    @Override
    public javax.swing.JMenuItem getMenuItem()
    {
        return mParentMenuItem;
    }
    @Override
    public javax.swing.JPanel getPanel()
    {
        return this;
    }
    public void deinit()
    {
        init = false;
    }
    /**
     * Creates new form DissiPanel
     */
    public  CompareDissiPanel() {
        initComponents();
        jEditorPane1.setEditable(false);
        jEditorPane1.setContentType("text/html");
        initTable();
        jLabel3.setVisible(false);
        setupKeyEvents();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItemCode = new javax.swing.JMenuItem();
        jMenuItemByte = new javax.swing.JMenuItem();
        jMenuItemWord = new javax.swing.JMenuItem();
        jMenuItemChar = new javax.swing.JMenuItem();
        jMenuItemUngroup = new javax.swing.JMenuItem();
        jMenuItemJoin = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItemC9 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItemRemove = new javax.swing.JMenuItem();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jButtonSearchNext = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonSearchPrevious = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jTextFieldCommand = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSource = buildTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableSource1 = buildTable();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTileFile = new javax.swing.JTextField();
        jButtonFileSelect1 = new javax.swing.JButton();
        jTextFieldTileFile1 = new javax.swing.JTextField();
        jButtonFileSelect2 = new javax.swing.JButton();

        jPopupMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPopupMenu1MouseExited(evt);
            }
        });

        jMenuItemCode.setText("cast to code");
        jMenuItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCodeActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemCode);

        jMenuItemByte.setText("cast to byte");
        jMenuItemByte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemByteActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemByte);

        jMenuItemWord.setText("cast to word");
        jMenuItemWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemWordActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemWord);

        jMenuItemChar.setText("cast to char");
        jMenuItemChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCharActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemChar);

        jMenuItemUngroup.setText("ungroup");
        jMenuItemUngroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUngroupActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemUngroup);

        jMenuItemJoin.setText("join (same data types)");
        jMenuItemJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJoinActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemJoin);

        jMenu1.setText("join #");

        jMenuItem1.setText("2");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("3");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("4");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("5");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("6");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jPopupMenu1.add(jMenu1);

        jMenu2.setText("DP");

        jMenuItem6.setText("$C8");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItemC9.setText("$C9");
        jMenuItemC9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemC9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemC9);

        jMenuItem7.setText("$D0");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jPopupMenu1.add(jMenu2);

        jMenuItemRemove.setText("remove");
        jMenuItemRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoveActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemRemove);

        setName("dissy"); // NOI18N

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("only full instructions");
        jCheckBox2.setToolTipText("Memory locations that \"belong\" to other mnemonics are not shown.");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("no unkown");
        jCheckBox1.setToolTipText("<html>Don't show locations that are \"unkown\" (not read from file), this <b>allways</b> includes RAM!<BR>(Since disassembled data is static)</html>\n"); // NOI18N
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonSearchNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/malban/vide/images/resultset_next.png"))); // NOI18N
        jButtonSearchNext.setToolTipText("search forward");
        jButtonSearchNext.setMargin(new java.awt.Insets(0, 1, 0, -1));
        jButtonSearchNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchNextActionPerformed(evt);
            }
        });

        jTextFieldSearch.setToolTipText("searches in labels and in comments (case independent)");
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });

        jLabel2.setText("search:");

        jButtonSearchPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/malban/vide/images/resultset_previous.png"))); // NOI18N
        jButtonSearchPrevious.setToolTipText("search backwards");
        jButtonSearchPrevious.setMargin(new java.awt.Insets(0, 1, 0, -1));
        jButtonSearchPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchPreviousActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("not found");

        jTextField1.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        jTextField1.setText("$0000");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("start:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("end:");

        jTextField2.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        jTextField2.setText("$ffff");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("CRC32-A:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("CRC32-B:");

        jTextField4.setEditable(false);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearchPrevious)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearchNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel7))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonSearchNext, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))))
                    .addComponent(jButtonSearchPrevious)))
        );

        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(1.0);

        jPanel3.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.setSize(new java.awt.Dimension(50, 50));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jEditorPane1.setEditable(false);
        jScrollPane3.setViewportView(jEditorPane1);

        jTextFieldCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCommandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
            .addComponent(jTextFieldCommand)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jTextFieldCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        jSplitPane1.setBottomComponent(jPanel3);

        jTableSource.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSource.setShowHorizontalLines(false);
        jTableSource.setShowVerticalLines(false);
        jTableSource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableSourceMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSource);

        jTableSource1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSource1.setShowHorizontalLines(false);
        jTableSource1.setShowVerticalLines(false);
        jTableSource1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableSource1MousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(jTableSource1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane4)
        );

        jSplitPane1.setLeftComponent(jPanel4);

        jLabel5.setText("Bin File");

        jTextFieldTileFile.setText("/Users/chrissalo/NetBeansProjects/Veccy/codelib/CompleteReleases/Ville Krumlinde/thrust.org/thrust.bin");
        jTextFieldTileFile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTileFileFocusLost(evt);
            }
        });
        jTextFieldTileFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTileFileActionPerformed(evt);
            }
        });

        jButtonFileSelect1.setText("...");
        jButtonFileSelect1.setMargin(new java.awt.Insets(0, 1, 0, -1));
        jButtonFileSelect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFileSelect1ActionPerformed(evt);
            }
        });

        jTextFieldTileFile1.setText("/Users/chrissalo/NetBeansProjects/Veccy/codelib/CompleteReleases/Ville Krumlinde/Thrust.bin");
        jTextFieldTileFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTileFile1ActionPerformed(evt);
            }
        });

        jButtonFileSelect2.setText("...");
        jButtonFileSelect2.setMargin(new java.awt.Insets(0, 1, 0, -1));
        jButtonFileSelect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFileSelect2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTileFile, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFileSelect1)
                .addGap(27, 27, 27)
                .addComponent(jTextFieldTileFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFileSelect2)
                .addGap(287, 287, 287)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jTextFieldTileFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFileSelect1)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTileFile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFileSelect2))
                .addGap(4, 4, 4)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        correctModel();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if (model!=null)
        {
            model.setFullDisplay(!jCheckBox2.isSelected());
        }
        if (model1!=null)
        {
            model1.setFullDisplay(!jCheckBox2.isSelected());
        }
        correctModel();
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jTableSourceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSourceMousePressed
        popupSource = jTableSource;
        if (evt.getButton() == MouseEvent.BUTTON3)
        {
            jPopupMenu1.show(jTableSource, evt.getX()-20,evt.getY()-20);
        }       
        
        if (evt.getClickCount() == 2) 
        {
            JTable table =(JTable) evt.getSource();
            Point p = evt.getPoint();
            int row = table.rowAtPoint(p);
            int col = table.columnAtPoint(p);
            if (col == 8) // zeiger auf adresse
            {
                MemoryInformation memInfo = model.getValueAt(row);
                boolean bit8 = false;
                String adr = (String) model.getValueAt( row,  col);
                if (adr.trim().length() <1) return;
                if (adr.trim().length() <4) bit8 = true;
                int a = DASM6809.toNumber(adr);
                int current = memInfo.address;
                
                if (bit8) a += current;
                goAddress(a,true, true, true);
            }
        }

        
    }//GEN-LAST:event_jTableSourceMousePressed

    ArrayList<Integer> rowStack = new ArrayList<Integer>();
    int rowStackPosition = -1;
    
    int getTopRow()
    {
        JViewport viewport = jScrollPane2.getViewport();

        Point p = viewport.getViewPosition();
        return jTableSource.rowAtPoint(p);   
    }
    
    private void jPopupMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPopupMenu1MouseExited
        jPopupMenu1.setVisible(false);
    }//GEN-LAST:event_jPopupMenu1MouseExited
    
    private void jMenuItemByteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemByteActionPerformed
        updateToNewType(popupSource, MemoryInformation.DIS_TYPE_DATA_BYTE, 1);
    }//GEN-LAST:event_jMenuItemByteActionPerformed

    private void jMenuItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCodeActionPerformed

        updateToNewType(popupSource,MemoryInformation.DIS_TYPE_DATA_INSTRUCTION_GENERAL, 1);
    }//GEN-LAST:event_jMenuItemCodeActionPerformed

    private void jMenuItemCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCharActionPerformed
        updateToNewType(popupSource,MemoryInformation.DIS_TYPE_DATA_CHAR, 1);
    }//GEN-LAST:event_jMenuItemCharActionPerformed

    private void jMenuItemWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemWordActionPerformed
        updateToNewType(popupSource,MemoryInformation.DIS_TYPE_DATA_WORD, 2);
    }//GEN-LAST:event_jMenuItemWordActionPerformed

    private void jMenuItemUngroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUngroupActionPerformed
        joinData(popupSource,1);
    }//GEN-LAST:event_jMenuItemUngroupActionPerformed
    
    private void jMenuItemJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJoinActionPerformed
        JTable table = popupSource;
        int[] selected = table.getSelectedRows();
        MemoryInformationTableModel model = (MemoryInformationTableModel) table.getModel();
        
        int max = 0;
        for (int row: selected)
        {
            MemoryInformation memInfo = model.getValueAt(row);
            int len = memInfo.length;
            for (int a=memInfo.address; a<memInfo.address+len; a++)
            {
                max++;
            }
        }        
        joinData(table,max);
    
    }//GEN-LAST:event_jMenuItemJoinActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        joinData(popupSource,2);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        joinData(popupSource,3);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        joinData(popupSource,4);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        joinData(popupSource,5);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        joinData(popupSource,6);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        updateToNewDP(popupSource,0xc8);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        updateToNewDP(popupSource,0xd0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItemC9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemC9ActionPerformed
        updateToNewDP(popupSource,0xc9);
    }//GEN-LAST:event_jMenuItemC9ActionPerformed

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        jButtonSearchNextActionPerformed(null);
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jButtonSearchPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchPreviousActionPerformed
        jLabel3.setVisible(false);
        int searchStart = 0;
        String text = jTextFieldSearch.getText();
        if (text.trim().length() == 0) return;
        int[] selected = jTableSource.getSelectedRows();
        MemoryInformationTableModel model = (MemoryInformationTableModel) jTableSource.getModel();
        if (selected.length!= 0) 
            searchStart = model.getValueAt(selected[0]).address-1;
        if (searchStart<=0) searchStart = 65535;
        int adr = searchForString(searchStart, text, false);
        int row = model.getNearestVisibleRow(adr);
        if (row == -1) return;
        
        goRow(row, true);

    }//GEN-LAST:event_jButtonSearchPreviousActionPerformed

    private void jButtonSearchNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchNextActionPerformed
        jLabel3.setVisible(false);
        int searchStart = 0;
        String text = jTextFieldSearch.getText();
        if (text.trim().length() == 0) return;
        int[] selected = jTableSource.getSelectedRows();
        MemoryInformationTableModel model = (MemoryInformationTableModel) jTableSource.getModel();
        if (selected.length!= 0) 
            searchStart = model.getValueAt(selected[0]).address+1;
        if (searchStart>=65536) searchStart = 0;
        int adr = searchForString(searchStart, text, true);
        int row = model.getNearestVisibleRow(adr);
        if (row == -1) return;
        
        goRow(row, true);
    }//GEN-LAST:event_jButtonSearchNextActionPerformed

    ArrayList<String> commandHistory = new ArrayList<String>();
    int commandHistoryPosition = -1;
    public void commandHistoryNext()
    {
        if (commandHistoryPosition==-1) return; // we have no history
        if (commandHistoryPosition == commandHistory.size()-1)
        {
            // new is allways empty
            jTextFieldCommand.setText("");
            commandHistoryPosition = -1;
            return;
        }
        commandHistoryPosition++;
        jTextFieldCommand.setText(commandHistory.get(commandHistoryPosition));
    }
    public void commandHistoryPrevious()
    {
        if (commandHistoryPosition==0) return; // we have no further history
        if (commandHistory.size()==0) return;
        if (commandHistoryPosition==-1)  // we are not yet in  history
        {
            commandHistoryPosition = commandHistory.size()-1;
            jTextFieldCommand.setText(commandHistory.get(commandHistoryPosition));
            return;
        }
        commandHistoryPosition--;
        jTextFieldCommand.setText(commandHistory.get(commandHistoryPosition));
    }
    
    private void jTextFieldCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCommandActionPerformed
        
        commandHistoryPosition = -1;
        commandHistory.add(jTextFieldCommand.getText());
        String command = jTextFieldCommand.getText();
        jTextFieldCommand.setText("");
    }//GEN-LAST:event_jTextFieldCommandActionPerformed

    private void jTextFieldTileFileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTileFileFocusLost
        jTextFieldTileFileActionPerformed(null);
    }//GEN-LAST:event_jTextFieldTileFileFocusLost

    private void jTextFieldTileFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTileFileActionPerformed

        String file = jTextFieldTileFile.getText().trim();
        String _class = "";
        if (file.length() == 0) return;
        
        String text = dis(jTextFieldTileFile.getText(), de.malban.util.UtilityString.Int0(jTextFieldTileFile.getText()), false);
        correctModel();
        calcCRC();

    }//GEN-LAST:event_jTextFieldTileFileActionPerformed

    private void jButtonFileSelect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFileSelect1ActionPerformed
        InternalFrameFileChoser fc = new de.malban.gui.dialogs.InternalFrameFileChoser();
        fc.setCurrentDirectory(new java.io.File("."+File.separator));
        int r = fc.showOpenDialog(Configuration.getConfiguration().getMainFrame());
        if (r != InternalFrameFileChoser.APPROVE_OPTION) return;
        String name = fc.getSelectedFile().getAbsolutePath();
        jTextFieldTileFile.setText(name);
        jTextFieldTileFileActionPerformed(null);
    }//GEN-LAST:event_jButtonFileSelect1ActionPerformed

    private void jTextFieldTileFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTileFile1ActionPerformed
        String file = jTextFieldTileFile1.getText().trim();
        String _class = "";
        if (file.length() == 0) return;
        
        String text = dis(jTextFieldTileFile1.getText(), de.malban.util.UtilityString.Int0(jTextFieldTileFile1.getText()), true);
        correctModel();
        calcCRC();
    }//GEN-LAST:event_jTextFieldTileFile1ActionPerformed

    private void jButtonFileSelect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFileSelect2ActionPerformed
        InternalFrameFileChoser fc = new de.malban.gui.dialogs.InternalFrameFileChoser();
        fc.setCurrentDirectory(new java.io.File("."+File.separator));
        int r = fc.showOpenDialog(Configuration.getConfiguration().getMainFrame());
        if (r != InternalFrameFileChoser.APPROVE_OPTION) return;
        String name = fc.getSelectedFile().getAbsolutePath();
        jTextFieldTileFile1.setText(name);
        jTextFieldTileFile1ActionPerformed(null);
    }//GEN-LAST:event_jButtonFileSelect2ActionPerformed

    private void jTableSource1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSource1MousePressed
        popupSource = jTableSource1;
        if (evt.getButton() == MouseEvent.BUTTON3)
        {
            jPopupMenu1.show(jTableSource1, evt.getX()-20,evt.getY()-20);
        }        
        if (evt.getClickCount() == 2) 
        {
            JTable table =(JTable) evt.getSource();
            Point p = evt.getPoint();
            int row = table.rowAtPoint(p);
            int col = table.columnAtPoint(p);
            if (col == 8) // zeiger auf adresse
            {
                MemoryInformation memInfo = model.getValueAt(row);
                boolean bit8 = false;
                String adr = (String) model.getValueAt( row,  col);
                if (adr.trim().length() <1) return;
                if (adr.trim().length() <4) bit8 = true;
                int a = DASM6809.toNumber(adr);
                int current = memInfo.address;
                
                if (bit8) a += current;
                goAddress(a,true, true, true);
            }
        }
    }//GEN-LAST:event_jTableSource1MousePressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        calcCRC();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        calcCRC();
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        calcCRC();
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        calcCRC();
    }//GEN-LAST:event_jTextField2FocusLost

    private void jMenuItemRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoveActionPerformed
        // remove selected addresses from table (visible)
        JTable table = popupSource;
        
        int[] selected = table.getSelectedRows();
        MemoryInformationTableModel model = (MemoryInformationTableModel) table.getModel();
        
        for (int row: selected)
        {
            MemoryInformation memInfo = model.getValueAt(row);
            int len = memInfo.length;
            for (int a=memInfo.address; a<memInfo.address+len; a++)
            {
                dasm.myMemory.memMap.get(a).visible = false;
                dasm1.myMemory.memMap.get(a).visible = false;
            }
        }
        correctModel();
    }//GEN-LAST:event_jMenuItemRemoveActionPerformed

    void spaceTo(StringBuilder s, int posNow, int upTo)
    {
        while (posNow++<upTo) s.append(" ");
    }
  
    private int searchForString(int start, String text, boolean forward)
    {
        int foundAt = -1;
        int addi = forward?1:-1;
            
        for (int i=start; (((i&0xffff) !=0) || (i==start)); i+=addi)
        {
            MemoryInformation memInfo =  dasm.myMemory.memMap.get(i);
            for (String l: memInfo.labels)
            {
                if (l.toLowerCase().indexOf(text.toLowerCase())>=0)
                {
                    foundAt = i;
                    jLabel3.setVisible(true);
                    jLabel3.setForeground(Color.black);
                    jLabel3.setText("Found in label at: " + String.format("$%04X",i&0xffff ));
                    break;
                }
            }
            if (foundAt!=-1) break;
            for (String c: memInfo.comments)
            {
                if (c.toLowerCase().indexOf(text.toLowerCase())>=0)
                {
                    foundAt = i;
                    jLabel3.setVisible(true);
                    jLabel3.setForeground(Color.black);
                    jLabel3.setText("Found in comment at: " + String.format("$%04X",i&0xffff ));
                    break;
                }
            }
            if (foundAt!=-1) break;
        }
        if (foundAt == -1)
        {
            jLabel3.setVisible(true);
            jLabel3.setForeground(Color.red);
            jLabel3.setText("not found");
        }

        return foundAt;
    }
    void updateToNewDP(JTable table, int dp)
    {
        int[] selected = table.getSelectedRows();
        MemoryInformationTableModel model = (MemoryInformationTableModel) table.getModel();
        
        DASM6809 da;
        if (table == jTableSource) da = dasm; else da = dasm1;
        int max = 0;
        for (int row: selected)
        {
            MemoryInformation memInfo = model.getValueAt(row);
            int len = memInfo.length;
            for (int a=memInfo.address; a<memInfo.address+len; a++)
            {
                // join / ungroup makes no sense for NON code
                if (da.myMemory.memMap.get(a).disType <MemoryInformation.DIS_TYPE_DATA_INSTRUCTION_1_LENGTH) continue;

                da.myMemory.memMap.get(a).directPageAddress = dp;

                da.myMemory.memMap.get(a).disType = MemoryInformation.DIS_TYPE_DATA_INSTRUCTION_GENERAL;
                da.myMemory.memMap.get(a).belongsToInstruction = null;
                da.myMemory.memMap.get(a).disassembledMnemonic = "";
                da.myMemory.memMap.get(a).disassembledOperand = "";
                da.myMemory.memMap.get(a).page = -1;
                da.myMemory.memMap.get(a).hexDump = "";
                da.myMemory.memMap.get(a).isInstructionByte = 0;
                da.myMemory.memMap.get(a).referingToAddress = -1;
                da.myMemory.memMap.get(a).referingAddressMode = -1;
                da.myMemory.memMap.get(a).length = 1;
                da.myMemory.memMap.get(a).done = false;
                da.myMemory.memMap.get(a).familyBytes.clear();
                
            }
        }        
        
        dasm.reDisassemble(false);
        updateTable();        
    }
    void updateToNewType(JTable table, int type, int l)
    {
        int[] selected = table.getSelectedRows();
        MemoryInformationTableModel model = (MemoryInformationTableModel) table.getModel();
        
        DASM6809 da;
        if (table == jTableSource) da = dasm; else da = dasm1;
        for (int row: selected)
        {
            MemoryInformation memInfo = model.getValueAt(row);
            int len = memInfo.length;
            for (int a=memInfo.address; a<memInfo.address+len; a++)
            {
                da.myMemory.memMap.get(a).disType = type;
                da.myMemory.memMap.get(a).belongsToInstruction = null;
                da.myMemory.memMap.get(a).disassembledMnemonic = "";
                da.myMemory.memMap.get(a).disassembledOperand = "";
                da.myMemory.memMap.get(a).page = -1;
                da.myMemory.memMap.get(a).hexDump = "";
                da.myMemory.memMap.get(a).isInstructionByte = 0;
                da.myMemory.memMap.get(a).referingToAddress = -1;
                da.myMemory.memMap.get(a).referingAddressMode = -1;
                da.myMemory.memMap.get(a).length = l;
                da.myMemory.memMap.get(a).done = false;
                da.myMemory.memMap.get(a).familyBytes.clear();
            }
        }
        da.reDisassemble(false);

        updateTable();        
    }
    private void joinData(JTable table, int ll)
    {
        int[] selected = table.getSelectedRows();
        MemoryInformationTableModel model = (MemoryInformationTableModel) table.getModel();
        
        DASM6809 da;
        if (table == jTableSource) da = dasm; else da = dasm1;
        
        for (int row: selected)
        {
            MemoryInformation memInfo = model.getValueAt(row);
            int len = memInfo.length;
            for (int a=memInfo.address; a<memInfo.address+len; a++)
            {
                // join / ungroup makes no sense for code
                if (da.myMemory.memMap.get(a).disType >=MemoryInformation.DIS_TYPE_DATA_INSTRUCTION_1_LENGTH) continue;
                
                da.myMemory.memMap.get(a).disTypeCollectionMax = ll;
                
                da.myMemory.memMap.get(a).disassembledMnemonic = "";
                da.myMemory.memMap.get(a).disassembledOperand = "";
                da.myMemory.memMap.get(a).page = -1;
                da.myMemory.memMap.get(a).hexDump = "";
                da.myMemory.memMap.get(a).isInstructionByte = 0;
                da.myMemory.memMap.get(a).referingToAddress = -1;
                da.myMemory.memMap.get(a).referingAddressMode = -1;
                da.myMemory.memMap.get(a).length = 1;
                da.myMemory.memMap.get(a).done = false;
                da.myMemory.memMap.get(a).familyBytes.clear();
            }
        }
        da.reDisassemble(false);
        updateTable();            
    }
    
    private void updateTable()
    {
        JViewport vp = (JViewport)jTableSource.getParent();
        Point pos = vp.getViewPosition();
        JViewport vp1 = (JViewport)jTableSource1.getParent();
        Point pos1 = vp1.getViewPosition();
        correctModel();
        vp.setViewPosition(pos);
        vp1.setViewPosition(pos1);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFileSelect1;
    private javax.swing.JButton jButtonFileSelect2;
    private javax.swing.JButton jButtonSearchNext;
    private javax.swing.JButton jButtonSearchPrevious;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItemByte;
    private javax.swing.JMenuItem jMenuItemC9;
    private javax.swing.JMenuItem jMenuItemChar;
    private javax.swing.JMenuItem jMenuItemCode;
    private javax.swing.JMenuItem jMenuItemJoin;
    private javax.swing.JMenuItem jMenuItemRemove;
    private javax.swing.JMenuItem jMenuItemUngroup;
    private javax.swing.JMenuItem jMenuItemWord;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTableSource;
    private javax.swing.JTable jTableSource1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldCommand;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldTileFile;
    private javax.swing.JTextField jTextFieldTileFile1;
    // End of variables declaration//GEN-END:variables

    boolean assumeVectrex = true;
    boolean createUnkownLabels = false;
    
    String loadedName = "";
    String loadedName1 = "";
    public String dis(String name, int startAddress, boolean useSecondtable)
    {
        if (!useSecondtable)
        {
            init = false;
            dasm.reset();
            loadedName = name;
            Path path = Paths.get(name);

            dasm.tryLoadList(name);
            dasm.tryLoadCNT(name);

            dasm.setCreateLabels(createUnkownLabels);
            String ret = "";
            try
            {
                byte[] data = Files.readAllBytes(path);

                ret = dasm.disassemble(data,startAddress, startAddress, assumeVectrex);
            }
            catch (Throwable e)
            {
                System.out.println(de.malban.util.Utility.getStackTrace(e));
                ret = dasm.disassemble(null,startAddress, startAddress, assumeVectrex);
            }

            correctModel();
            init = true;
            return ret;
        }
        init1 = false;
        dasm1.reset();
        loadedName1 = name;
        Path path = Paths.get(name);

        dasm1.tryLoadList(name);
        dasm1.tryLoadCNT(name);

        dasm1.setCreateLabels(createUnkownLabels);
        String ret = "";
        try
        {
            byte[] data = Files.readAllBytes(path);

            ret = dasm1.disassemble(data,startAddress, startAddress, assumeVectrex);
        }
        catch (Throwable e)
        {
            System.out.println(de.malban.util.Utility.getStackTrace(e));
            ret = dasm1.disassemble(null,startAddress, startAddress, assumeVectrex);
        }

        correctModel();
        init = true;
        return ret;
    }
    public boolean isInit()
    {
        return init;
    }
    public void correctModel()
    {
        if (model != null)
        {
            model.showAll();
            if (jCheckBox1.isSelected())
                model.reduceUnkown();
            if (jCheckBox2.isSelected())
                model.reduceCompleteInstructions();
            
            model.reduceInvisible();

            jTableSource.tableChanged(null);
            for (int i=0; i< model.getColumnCount(); i++)
            {
                jTableSource.getColumnModel().getColumn(i).setPreferredWidth(model.getColWidth(i));                
            }
            
        }

        if (model1 != null)
        {
            model1.showAll();
            if (jCheckBox1.isSelected())
                model1.reduceUnkown();
            if (jCheckBox2.isSelected())
                model1.reduceCompleteInstructions();
            
            model1.reduceInvisible();

            jTableSource1.tableChanged(null);
            for (int i=0; i< model1.getColumnCount(); i++)
            {
                jTableSource1.getColumnModel().getColumn(i).setPreferredWidth(model1.getColWidth(i));                
            }
            
        }
    
    }
    
    public void updateTableOnly()
    {
        jTableSource.repaint();
        jTableSource1.repaint();
    }
    
    public void goRow(int row, boolean forceTopRow)
    {
        if (!init) return;
        
        jTableSource.setRowSelectionInterval(row, row);
        if (forceTopRow)
            scrollToVisible(jTableSource, row,0) ;
        jTableSource.scrollRectToVisible(jTableSource.getCellRect(row, 0, true));
    }    
    public void goAddress(int address, boolean forceTopRow, boolean userGo, boolean forceUpdate)
    {
        if (!init) return;
        if (!forceUpdate) // single step e.g. always must update!
        {
            if (!userGo)
            {
                if (!updateEnabled) return;
            }
        }
        
        
        // select line in table and jump to display that!
        int row = model.getNearestVisibleRow( address);
        if (row == -1 ) return;
        // select
        jTableSource.setRowSelectionInterval(row, row);
        if (forceTopRow)
            scrollToVisible(jTableSource, row,0) ;
        // and jump there!
            jTableSource.scrollRectToVisible(jTableSource.getCellRect(row, 0, true));
    }
    public static void scrollToVisible(JTable table, int rowIndex, int vColIndex) 
    {
        // down
        JViewport vp = (JViewport)table.getParent();
        int bottomIndex = table.getModel().getRowCount()-1;
        table.setRowSelectionInterval(bottomIndex, bottomIndex);
        table.changeSelection(bottomIndex,0,false,false);
        Rectangle r = table.getCellRect(bottomIndex-1, 0, true);
        int vph = vp.getExtentSize().height;
        r.y += vph;
        table.scrollRectToVisible(r);

        
        // and UP!
        int currentSelectedRow = table.getSelectedRow();
        
        try{
          table.changeSelection(rowIndex,0,false,false);
          if(rowIndex > currentSelectedRow)
          {
            r = table.getCellRect(rowIndex-1, 0, true);
            vph = vp.getExtentSize().height;
            r.y += vph;
            table.scrollRectToVisible(r);
          }
        }catch(Exception e){/*error message*/}

    
    }
    public int getInstructionLengthAt(int address)
    {
        if (!init) return 1;
        return dasm.getInstructionLengthAt(address);
    }
    
    private void initTable()
    {
        model = dasm.getTableModel();
        model.smallMode = true;
        jTableSource.setModel(model);
        jTableSource.tableChanged(null);
        //jTableSource.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTableSource.setRowSelectionAllowed(true);
        jTableSource.setDefaultRenderer(Object.class, new DefaultTableCellRenderer()
        {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int col) 
            {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);

                if (table.getModel() instanceof MemoryInformationTableModel)
                {
                    MemoryInformationTableModel localModel = (MemoryInformationTableModel)table.getModel();
                    MemoryInformationTableModel otherModel;
                    if(localModel.equals(model1))otherModel=model;
                    else otherModel=model1;
                    
                    MemoryInformation memInfo = localModel.getValueAt(row);
                   
                    // compare row by number
                    String cmp1 = "";
                    if (otherModel.getRowCount()>row)
                        cmp1 = otherModel.getValueAt(row,2).toString();
                    String cmp2 = "";
                    if (localModel.getRowCount()>row)
                        cmp2 = localModel.getValueAt(row,2).toString();
                    
                    // compare row by address
                    String cmp3 = "";
                        
                    int arow = otherModel.getRowForAddress(memInfo.address);
                    if (arow != -1)
                    {
                        cmp3 = otherModel.getValueAt(arow,2).toString();
                    }
//                    if (!cmp1.equals(cmp2))
                    if (!cmp2.equals(cmp3))
                    {
                        setBackground(Color.RED);
                        // setForeground(Color.WHITE);
                    } 
                    else 
                    {
                        if (isSelected)
                        {
                            setBackground(table.getSelectionBackground());
                            setForeground(table.getSelectionForeground());
                            
                        }
                        else
                        {
                            Color back = localModel.getBackground(row, col);
                            Color fore = localModel.getForeground(row, col);
                            if (back != null)
                                setBackground(back);
                            else
                                setBackground(table.getBackground());
                            if (fore != null)
                                setForeground(fore);
                            else
                                setForeground(table.getForeground());
                        }
                    }       
                }
                return this;
            }   
        });        
        
        model1 = dasm1.getTableModel();
        model1.smallMode = true;
        jTableSource1.setModel(model1);
        jTableSource1.tableChanged(null);
        //jTableSource.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTableSource1.setRowSelectionAllowed(true);
        jTableSource1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer()
        {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int col) 
            {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);

                if (table.getModel() instanceof MemoryInformationTableModel)
                {
                    MemoryInformationTableModel localModel = (MemoryInformationTableModel)table.getModel();
                    MemoryInformationTableModel otherModel;
                    if(localModel.equals(model1))otherModel=model;
                    else otherModel=model1;
                    MemoryInformation memInfo = localModel.getValueAt(row);
                   
                    // compare row by number
                    String cmp1 = "";
                    if (otherModel.getRowCount()>row)
                        cmp1 = otherModel.getValueAt(row,2).toString();
                    String cmp2 = "";
                    if (localModel.getRowCount()>row)
                        cmp2 = localModel.getValueAt(row,2).toString();
                    
                    // compare row by address
                    String cmp3 = "";
                        
                    int arow = otherModel.getRowForAddress(memInfo.address);
                    if (arow != -1)
                    {
                        cmp3 = otherModel.getValueAt(arow,2).toString();
                    }
//                    if (!cmp1.equals(cmp2))
                    if (!cmp2.equals(cmp3))
                    {
                        setBackground(Color.RED);
                        // setForeground(Color.WHITE);
                    } 
                    else 
                    {
                        if (isSelected)
                        {
                            setBackground(table.getSelectionBackground());
                            setForeground(table.getSelectionForeground());
                            
                        }
                        else
                        {
                            Color back = localModel.getBackground(row, col);
                            Color fore = localModel.getForeground(row, col);
                            if (back != null)
                                setBackground(back);
                            else
                                setBackground(table.getBackground());
                            if (fore != null)
                                setForeground(fore);
                            else
                                setForeground(table.getForeground());
                        }
                    }       
                }
                return this;
            }   
        });      

        JScrollBar sBar1 = jScrollPane2.getVerticalScrollBar();
        JScrollBar sBar2 = jScrollPane4.getVerticalScrollBar();
        sBar2.setModel(sBar1.getModel()); //<--------------synchronize            
              
    }
    
    
    
    public int getCurrentAddress()
    {
        if (!init) return -1;
        int row = jTableSource.getSelectedRow();
        if (row == -1) return -1;
        MemoryInformationTableModel model = (MemoryInformationTableModel)jTableSource.getModel();
        MemoryInformation memInfo = model.getValueAt(row);
        return memInfo.address;
    }

    public MemoryInformation getMemoryInformation(int address)
    {
        return dasm.myMemory.memMap.get(address);
    }
    public Memory getMemory()
    {
        return dasm.myMemory;
    }
    
    public static String SID = "cdissi";
    public String getID()
    {
        return SID;
    }
    JTable buildTable()
    {
        JTable table = new JTable();       
        table.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);  
       return  table;
        
    }
    boolean keyEventsAreSet = false;
    private void setupKeyEvents()
    {
        if (keyEventsAreSet) return;
        keyEventsAreSet = true;

        jTextFieldCommand.getInputMap(WHEN_FOCUSED).put(KeyStroke.getKeyStroke(KeyEvent.VK_DOWN,0, false), "command next");
        jTextFieldCommand.getActionMap().put("command next", new AbstractAction() { public void actionPerformed(ActionEvent e) {   commandHistoryNext(); }});
        jTextFieldCommand.getInputMap(WHEN_FOCUSED).put(KeyStroke.getKeyStroke(KeyEvent.VK_UP,0, false), "command previous");
        jTextFieldCommand.getActionMap().put("command previous", new AbstractAction() { public void actionPerformed(ActionEvent e) {  commandHistoryPrevious(); }});
    }   
    private boolean updateEnabled = false;
    public void updateValues(boolean forceUpdate)
    {
        if (!forceUpdate)
            if (!updateEnabled) return;
        updateTableOnly();
    }
    public void setUpdateEnabled(boolean b)
    {
        updateEnabled = b;
    }
    
    // if we do that more often, we should build a lookup table for labels as a hashmap!
    int getLabelAddr(String label)
    {
        Memory mem = dasm.myMemory;
        
        for (int i=0; i<65536; i++)
        {
            MemoryInformation memInfo = mem.memMap.get(i);
            for (String l: memInfo.labels)
            {
                if (l.equals(label)) 
                    return i;
            }
        }
        return 0; // not successull
        
    }
    
    
    public void printMessage(String s, String type)
    {
        try
        {
            jEditorPane1.getDocument().insertString(jEditorPane1.getDocument().getLength(), s+"\n", TokenStyles.getStyle(type));
        } catch (Throwable e) { }
        jEditorPane1.setCaretPosition(jEditorPane1.getDocument().getLength());
    }
    
    static class SplitterLocation implements Serializable
    {
        int pos=0;
    }
    public Serializable getAdditionalStateinfo()
    {
        SplitterLocation sl = new SplitterLocation();
        sl.pos = jSplitPane1.getDividerLocation();
        return sl;
    }
    public void setAdditionalStateinfo(Serializable ser)
    {
        SplitterLocation sl = (SplitterLocation) ser;
        jSplitPane1.setDividerLocation(sl.pos);
    }
    private void calcCRC()
    {
        int start = DASM6809.toNumber(jTextField1.getText());
        int end = DASM6809.toNumber(jTextField2.getText());
        
        jTextField3.setText(""+dasm.myMemory.getCRC(start, end));
        jTextField4.setText(""+dasm1.myMemory.getCRC(start, end));
    
        
    }
}
